openapi: 3.0.0
info:
  description: Your API Description here
  version: 1.0.0
  title: API Docs Title
servers:
  - url: /api/v1
  
paths:
  /users:
    get:
      summary: Returns a list of users.
      operationId: getAllUsers #This is the function that would be called from ./api/controllers/index.js
      description: Optional extended description in CommonMark or HTML
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
